/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.poly.model;

import com.poly.dao.NhanVienDAO;
import com.poly.entity.NhanVien;
//import com.poly.utils.XAuth;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import org.openide.util.Exceptions;

/**
 *
 * @author Nhu Y
 */
public class DangNhapJFrame extends javax.swing.JFrame {
        Connection ketnoi;
        NhanVienDAO nvdao = new NhanVienDAO();
    /**
     * Creates new form DangNhapJFrame
     */
    public DangNhapJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        txtTenTk = new javax.swing.JTextField();
        lblQuenMk = new javax.swing.JLabel();
        lblThoat = new javax.swing.JLabel();
        btnDangNhap = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(DangNhapJFrame.class, "DangNhapJFrame.jLabel2.text")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 20, 160, 32);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(DangNhapJFrame.class, "DangNhapJFrame.jLabel3.text")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 80, 110, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(DangNhapJFrame.class, "DangNhapJFrame.jLabel4.text")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 170, 70, 20);

        txtPass.setText(org.openide.util.NbBundle.getMessage(DangNhapJFrame.class, "DangNhapJFrame.txtPass.text")); // NOI18N
        getContentPane().add(txtPass);
        txtPass.setBounds(110, 200, 370, 40);

        txtTenTk.setText(org.openide.util.NbBundle.getMessage(DangNhapJFrame.class, "DangNhapJFrame.txtTenTk.text")); // NOI18N
        getContentPane().add(txtTenTk);
        txtTenTk.setBounds(110, 110, 370, 40);

        lblQuenMk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblQuenMk.setForeground(new java.awt.Color(255, 255, 255));
        org.openide.awt.Mnemonics.setLocalizedText(lblQuenMk, org.openide.util.NbBundle.getMessage(DangNhapJFrame.class, "DangNhapJFrame.lblQuenMk.text")); // NOI18N
        lblQuenMk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuenMkMouseClicked(evt);
            }
        });
        getContentPane().add(lblQuenMk);
        lblQuenMk.setBounds(110, 250, 120, 20);

        lblThoat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblThoat.setForeground(new java.awt.Color(255, 255, 255));
        org.openide.awt.Mnemonics.setLocalizedText(lblThoat, org.openide.util.NbBundle.getMessage(DangNhapJFrame.class, "DangNhapJFrame.lblThoat.text")); // NOI18N
        lblThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThoatMouseClicked(evt);
            }
        });
        getContentPane().add(lblThoat);
        lblThoat.setBounds(430, 250, 50, 20);

        btnDangNhap.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(btnDangNhap, org.openide.util.NbBundle.getMessage(DangNhapJFrame.class, "DangNhapJFrame.btnDangNhap.text")); // NOI18N
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        getContentPane().add(btnDangNhap);
        btnDangNhap.setBounds(240, 310, 130, 27);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wepik-export-20231108142252Lqnj.jpeg"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(DangNhapJFrame.class, "DangNhapJFrame.jLabel1.text")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 580, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:
        if (checknull() == true) {
            try {
                DangNhap();
            } catch (SQLException ex) {
                Exceptions.printStackTrace(ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Không được để trống");
        }
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void lblThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThoatMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {
            System.exit(0);
        }
    }//GEN-LAST:event_lblThoatMouseClicked

    private void lblQuenMkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuenMkMouseClicked
        // TODO add your handling code here:
        new QuenMatKhauJFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblQuenMkMouseClicked
 public void DangNhap() throws SQLException {
        KetNoiCSDL();
        String sql = "SELECT * FROM NhanVien where TenNhanVien =? and MatKhau = ?";
        PreparedStatement cauLenh = ketnoi.prepareStatement(sql);
        cauLenh.setString(1, txtTenTk.getText());
        cauLenh.setString(2, String.copyValueOf(txtPass.getPassword()));
        ResultSet ketQua = cauLenh.executeQuery();
        if (ketQua.next()) {
            JOptionPane.showMessageDialog(this, "Đăng nhập thành công!", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
            System.out.println(ketQua.getString(9));
            NhanVien nv = nvdao.selectById(txtTenTk.getText());
            //XAuth.user = nv;
            //String userID = XAuth.user.getTenNhanVien();
            //String role = XAuth.user.equals("ChucVu")? "Nhân Viên" : "Admin";
            //String hoTen = XAuth.user.getTenNhanVien();
            //new MainJFrame(userID, role, hoTen).setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Tên tài khoản hoặc mật khẩu sai", "Đăng nhập thất bại", JOptionPane.ERROR_MESSAGE);
        }
    }

    public boolean checknull() {
        String tendangnhap = txtTenTk.getText();
        String matkhau = txtPass.getText();

        if (tendangnhap.isEmpty() && matkhau.isEmpty()) {
            return false;
        } else {
            return true;
        }
    }

    public void KetNoiCSDL() throws SQLException {
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=quanlydonoithat;encrypt=true;trustServerCertificate=true";
            String user = "sa";
            String pass = "123";
            ketnoi = DriverManager.getConnection(url, user, pass);

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex);

        }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhapJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhapJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhapJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhapJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhapJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblQuenMk;
    private javax.swing.JLabel lblThoat;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtTenTk;
    // End of variables declaration//GEN-END:variables
}
