/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.poly.model;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Nhu Y
 */
public class DoiMatKhauJFrame extends javax.swing.JFrame {
         Connection ketnoi;
    /**
     * Creates new form DoiMatKhau
     */
    public DoiMatKhauJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPass1 = new javax.swing.JPasswordField();
        txtPass2 = new javax.swing.JPasswordField();
        lblQuaylai = new javax.swing.JLabel();
        btnDangNhap = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ĐỔI MẬT KHẨU");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(160, 10, 190, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mật khẩu mới:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 60, 120, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nhập lại mật khẩu mới:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 130, 160, 20);
        jPanel1.add(txtPass1);
        txtPass1.setBounds(70, 80, 350, 40);
        jPanel1.add(txtPass2);
        txtPass2.setBounds(70, 160, 350, 40);

        lblQuaylai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblQuaylai.setForeground(new java.awt.Color(255, 255, 255));
        lblQuaylai.setText("Quay lại");
        lblQuaylai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuaylaiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQuaylaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuaylaiMouseExited(evt);
            }
        });
        jPanel1.add(lblQuaylai);
        lblQuaylai.setBounds(360, 210, 60, 20);

        btnDangNhap.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.setToolTipText("");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        jPanel1.add(btnDangNhap);
        btnDangNhap.setBounds(160, 250, 140, 40);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/banner5.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 330);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void lblQuaylaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuaylaiMouseClicked
        // TODO add your handling code here:
        new DangNhapJFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblQuaylaiMouseClicked

    private void lblQuaylaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuaylaiMouseEntered
        // TODO add your handling code here:
          lblQuaylai.setForeground(Color.red);
    }//GEN-LAST:event_lblQuaylaiMouseEntered

    private void lblQuaylaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuaylaiMouseExited
        // TODO add your handling code here:
         lblQuaylai.setForeground(Color.white);
    }//GEN-LAST:event_lblQuaylaiMouseExited
 public void KetNoiCSDL() throws SQLException {
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url = "jdbc:sqlserver://localhost:1433;databaseName=quanlydonoithat;encrypt=true;trustServerCertificate=true";
            String user = "sa";
            String pass = "123";
            ketnoi = DriverManager.getConnection(url, user, pass);

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex);

        }

    }
    public void doimatkhau(String TenNhanVien, String currentPassword, String newPassword) throws SQLException {
    KetNoiCSDL();
    try {
        // Kiểm tra xem người dùng có quyền đổi mật khẩu hay không (ví dụ: dựa trên username và currentPassword)
        if (kiemTraQuyenDoiMatKhau(TenNhanVien, currentPassword)) {
            String sql = "UPDATE NhanVien SET MatKhau = ? WHERE TenNhanVien = ?";
            PreparedStatement cauLenh = ketnoi.prepareStatement(sql);
            
            // Thiết lập giá trị cho các tham số trong câu lệnh SQL
            cauLenh.setString(1, newPassword);
            cauLenh.setString(2, TenNhanVien);
            
            // Thực hiện cập nhật mật khẩu trong CSDL
            cauLenh.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Mật khẩu đã được cập nhật thành công!");
        } else {
            JOptionPane.showMessageDialog(this, "Sai thông tin đăng nhập hoặc không có quyền đổi mật khẩu.");
        }
    } finally {
        // Đảm bảo đóng kết nối sau khi sử dụng
        ketnoi.close();
    }
}

private boolean kiemTraQuyenDoiMatKhau(String TenNhanVien, String currentPassword) throws SQLException {
    String sql = "SELECT * FROM NhanVien WHERE TenNhanVien = ? AND Matkhau = ?";
    PreparedStatement cauLenh = ketnoi.prepareStatement(sql);
    
    // Thiết lập giá trị cho các tham số trong câu lệnh SQL
    cauLenh.setString(1, TenNhanVien);
    cauLenh.setString(2, currentPassword);
    
    ResultSet ketQua = cauLenh.executeQuery();
    
    // Nếu có kết quả, người dùng tồn tại và thông tin đăng nhập đúng
    return ketQua.next();
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoiMatKhauJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblQuaylai;
    private javax.swing.JPasswordField txtPass1;
    private javax.swing.JPasswordField txtPass2;
    // End of variables declaration//GEN-END:variables
}
