/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.poly.model;

import com.poly.dao.NhanVienDAO;
import com.poly.utils.XAuth;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Nhu Y
 */
public class DoiMatKhauJFrame extends javax.swing.JFrame {
         NhanVienDAO nvdao = new NhanVienDAO();
    /**
     * Creates new form DoiMatKhau
     */
    public DoiMatKhauJFrame() {
        initComponents();
    }
public boolean check(){
      if(txtPass1.getText().equals("")){
          JOptionPane.showMessageDialog(this, "Không dể trống mật khẩu mới");
          return false;
      }
       if(txtPass2.getText().equals("")){
          JOptionPane.showMessageDialog(this, "Không dể trống mật xác nhận");
          return false;
      }
       return true;
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPass1 = new javax.swing.JPasswordField();
        txtPass2 = new javax.swing.JPasswordField();
        lblQuaylai = new javax.swing.JLabel();
        btnDangNhap = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setText("ĐỔI MẬT KHẨU");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(160, 10, 190, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Mật khẩu mới:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(160, 80, 120, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Nhập lại mật khẩu mới:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(160, 160, 160, 20);
        jPanel1.add(txtPass1);
        txtPass1.setBounds(160, 110, 320, 40);
        jPanel1.add(txtPass2);
        txtPass2.setBounds(160, 190, 320, 40);

        lblQuaylai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblQuaylai.setText("Quay lại");
        lblQuaylai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuaylaiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQuaylaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuaylaiMouseExited(evt);
            }
        });
        jPanel1.add(lblQuaylai);
        lblQuaylai.setBounds(420, 240, 60, 20);

        btnDangNhap.setBackground(new java.awt.Color(204, 204, 255));
        btnDangNhap.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.setToolTipText("");
        btnDangNhap.setBorder(null);
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        jPanel1.add(btnDangNhap);
        btnDangNhap.setBounds(220, 260, 140, 40);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/account.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 80, 130, 150);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:
         String matKhau1 = txtPass1.getText();
        String matKhau2 = txtPass2.getText();
        boolean isMatch = matKhau1.equals(matKhau2);
        if( check()){
        if (isMatch) {
            XAuth.user.getMaNhanVien();
            nvdao.update(txtPass1.getText(), XAuth.user.getMaNhanVien());
            JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công");
            String userID = XAuth.user.getMaNhanVien();
            String role = String.valueOf(XAuth.user.isChucVu()).equals("true") ? "Admin" : "Nhân Viên";
            String hoTen = XAuth.user.getTenNhanVien();
            new MainJFrame(userID, role, hoTen).setVisible(true);
            this.dispose();
        }else {
            JOptionPane.showMessageDialog(this, "Mật khẩu không trùng khớp");
        }
        
        }
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void lblQuaylaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuaylaiMouseClicked
        // TODO add your handling code here:
        new DangNhapJFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblQuaylaiMouseClicked

    private void lblQuaylaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuaylaiMouseEntered
        // TODO add your handling code here:
          lblQuaylai.setForeground(Color.red);
    }//GEN-LAST:event_lblQuaylaiMouseEntered

    private void lblQuaylaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuaylaiMouseExited
        // TODO add your handling code here:
         lblQuaylai.setForeground(Color.white);
    }//GEN-LAST:event_lblQuaylaiMouseExited
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhauJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoiMatKhauJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblQuaylai;
    private javax.swing.JPasswordField txtPass1;
    private javax.swing.JPasswordField txtPass2;
    // End of variables declaration//GEN-END:variables
}
